# Generated by Django 5.2.1 on 2025-05-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate_reference_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
